# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-23 16:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Impediment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('resolution_date', models.DateField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('real_start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('real_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('role', models.CharField(blank=True, default='user', max_length=100)),
                ('avatar', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(db_column='id_sprint', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='scrum.Project')),
                ('responsible', models.ForeignKey(blank=True, db_column='id_scrumuser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='scrum.ScrumUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_column='id_task', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.Project')),
                ('responsible', models.ForeignKey(blank=True, db_column='id_scrumuser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.ScrumUser')),
                ('sprint', models.ForeignKey(blank=True, db_column='id_sprint', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.Sprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeContinuousActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(blank=True, default='', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='administrative_responsible',
            field=models.ForeignKey(blank=True, db_column='id_scrumuser_administrative', null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.ScrumUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_responsible',
            field=models.ForeignKey(blank=True, db_column='id_scrumuser_technical', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='scrum.ScrumUser'),
        ),
        migrations.AddField(
            model_name='impediment',
            name='sprint',
            field=models.ForeignKey(blank=True, db_column='id_sprint', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impediments', to='scrum.Sprint'),
        ),
        migrations.AddField(
            model_name='impediment',
            name='task',
            field=models.ForeignKey(blank=True, db_column='id_task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impediments', to='scrum.Task'),
        ),
        migrations.AddField(
            model_name='continuousactivity',
            name='responsible',
            field=models.ForeignKey(blank=True, db_column='id_scrumuser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continuous_activities', to='scrum.ScrumUser'),
        ),
        migrations.AddField(
            model_name='continuousactivity',
            name='typeContinuousActivity',
            field=models.ForeignKey(blank=True, db_column='id_typeContinuousActivity', null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.ScrumUser'),
        ),
    ]
