# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 21:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impediment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_date', models.DateField(default=datetime.datetime.now)),
                ('resolution_date', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('role', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(db_column='id_sprint', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('end', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_column='id_task', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('sprint', models.ForeignKey(blank=True, db_column='id_sprint', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.Sprint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='impediment',
            name='sprint',
            field=models.ForeignKey(blank=True, db_column='id_sprint', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impediments', to='scrum.Sprint'),
        ),
        migrations.AddField(
            model_name='impediment',
            name='task',
            field=models.ForeignKey(blank=True, db_column='id_task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impediments', to='scrum.Task'),
        ),
    ]
