# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='responsible',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='scrum.ScrumUser'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.ScrumUser'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
