# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_auto_20170925_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('real_start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('real_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='real_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='responsible',
            field=models.ForeignKey(blank=True, db_column='id_scrumuser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='scrum.ScrumUser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(blank=True, db_column='id_scrumuser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.ScrumUser'),
        ),
    ]
