# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_auto_20170928_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, db_column='id_project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scrum.Project'),
        ),
    ]
