# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-29 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('type', models.IntegerField(blank=True, default='', null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('responsible', models.ForeignKey(blank=True, db_column='id_scrumuser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='continuous_activities', to='scrum.ScrumUser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
