# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_continuousactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impediment',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='impediment',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='administrative_responsible',
            field=models.ForeignKey(blank=True, db_column='id_scrumuser_administrative', null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.ScrumUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_responsible',
            field=models.ForeignKey(blank=True, db_column='id_scrumuser_technical', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='scrum.ScrumUser'),
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='ativo',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='scrumuser',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='scrumuser',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='scrumuser',
            name='role',
            field=models.CharField(blank=True, default='user', max_length=100),
        ),
    ]
